version: '3.8'

networks:
  edtech-network:
    driver: bridge

services:
  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "4000:4000"
    networks:
      - edtech-network

  frontend:
    build: .
    container_name: frontend
    ports:
      - "3000:3000"
   
    depends_on:
      - backend
    networks:
      - edtech-network
